/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestionfinanciere (void);
GtkWidget* create_lesfactures (void);
GtkWidget* create_statistique (void);
GtkWidget* create_window4 (void);
GtkWidget* create_donneclient (void);
GtkWidget* create_espaceemploye (void);
GtkWidget* create_prestation (void);
