/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestionfinanciere (void);
GtkWidget* create_lesfactures (void);
GtkWidget* create_statistique (void);
GtkWidget* create_donneclient (void);
GtkWidget* create_espaceemploye (void);
GtkWidget* create_prestation (void);
GtkWidget* create_acceuil (void);
GtkWidget* create_espaceadmin (void);
GtkWidget* create_espaceclient (void);
GtkWidget* create_moncompte (void);
GtkWidget* create_reclamation (void);
GtkWidget* create_factures (void);
GtkWidget* create_panier (void);
